Add LazyImportError
facebookincubator/cinder pull request #82
Opened 2022-06-24 15:53 UTC by chuanzzx

# Summary
Wrap every deferred import exception in a new exception type `LazyImportError`, chained to the original exception.

# Test Plan
- When Lazy Imports is not enabled, every error will change nothing.
- When Lazy Imports is enabled, every error cause by a (lazy) import action will wrap into `LazyImportError`. Thus, the error will show `LazyImportError` and link back to the original exception with tracebacks.

## Pre-req
Create `foo.py`, `value_error.py`, `run_foo.py`, and `run_value_error.py` under the same path of `python.exe`.

### foo.py
```
import applepie
applepie
```
### value_error.py
```
raise ValueError("")
```
### run_foo.py
```
import foo
foo
```
### run_value_error.py
```
import value_error
value_error
```

## Test without Lazy Imports
### Test ModuleNotFoundError
Run
```
./python.exe run_foo.py
```
Expected results:
```
Traceback (most recent call last):
  File "/Users/harperlin/Documents/GitHub/crashy_0623/run_foo.py", line 1, in <module>
    import foo
    ^^^^^^^^^^
  File "/Users/harperlin/Documents/GitHub/crashy_0623/foo.py", line 1, in <module>
    import applepie
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'applepie'
```

### Test ValueError
Run
```
./python.exe run_value_error.py
```
Expected results:
```
Traceback (most recent call last):
  File "/Users/harperlin/Documents/GitHub/crashy_0623/run_value_error.py", line 1, in <module>
    import value_error
    ^^^^^^^^^^^^^^^^^^
  File "/Users/harperlin/Documents/GitHub/crashy_0623/value_error.py", line 1, in <module>
    raise ValueError("")
    ^^^^^^^^^^^^^^^^^^^^
ValueError
```

## Test with Lazy Imports
### Test ModuleNotFoundError
Run
```
./python.exe -L run_foo.py
```
Expected results:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'applepie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harperlin/Documents/GitHub/crashy_0623/foo.py", line 2, in <module>
    applepie
    ^^^^^^^^
LazyImportError: Improper Module import causes this error when enabling Lazy Imports.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harperlin/Documents/GitHub/crashy_0623/run_foo.py", line 2, in <module>
    foo
    ^^^
LazyImportError: Improper Module import causes this error when enabling Lazy Imports.
```

### Test ValueError
Run
```
./python.exe -L run_value_error.py
```
Expected results:
```
Traceback (most recent call last):
  File "/Users/harperlin/Documents/GitHub/crashy_0623/value_error.py", line 1, in <module>
    raise ValueError("")
    ^^^^^^^^^^^^^^^^^^^^
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harperlin/Documents/GitHub/crashy_0623/run_value_error.py", line 2, in <module>
    value_error
    ^^^^^^^^^^^
LazyImportError: Improper Module import causes this error when enabling Lazy Imports.
```

2022-06-24 19:48 UTC, itamaro commented on Objects/exceptions.c
> +                         "Module import errors when enabling Lazy Imports.");
```suggestion
                         "Errors raised when loading a lazy import.");
```

2022-06-24 19:51 UTC, itamaro commented on Python/import.c
> +                                   "when enabling Lazy Imports.");
change error message to something like "Error occurred when loading a lazy import. Original import was at {file} {line}" (which would require adding file and line metadata to the lazy import object)

2022-06-24 19:54 UTC, itamaro requested changes
thanks, love the concise implementation!

left inline comments as discussed offline - let's also avoid chaining multiple lazy import errors

2022-06-24 20:51 UTC, Kronuz commented on Python/import.c
> +                _PyErr_FormatFromCause(PyExc_LazyImportError,
If you already have `tstate`, you could use `_PyErr_FormatFromCauseTstate` instead and pass it over. Additionally, you could move `_PyThreadState_GET` to the `else` block, so it's used only there.

However, the filename and the line you need to keep should be added to the `PyLazyImport` object, by the time it is created (when executing `IMPORT_NAME` opcode in `ceval.c` or here in `import.c`, when the object is created). You'll need to add a `PyObject` for the filename and an integer for the line number for that (to `PyLazyImport`), and use those here.

2022-06-24 22:22 UTC, Kronuz commented on Python/import.c
> +        ((PyLazyImport *)lazy_module)->lz_filename = code->co_filename;
I think you may need to do `Py_INCREF` here for this one.

2022-06-24 23:03 UTC, Kronuz approved these changes
<img src="https://media4.giphy.com/media/oobNzX5ICcRZC/giphy.gif"/>

2022-06-25 03:00 UTC, itamaro approved these changes

2022-06-25 03:02 UTC, merged